[package]
name = "iron-tut"
version = "0.1.0"
authors = ["Takeru Sato <type.in.type@gmail.com>"]

[dependencies]
hyper = "0.10"
iron = "0.5.1"
router = "0.5"
params = "0.6"
mime = "0.2"
typemap = "0.3"
lazy_static = "0.2"
